# Media Centre Pipeline (CI)

image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cd www
          - npm install
          - npm install --only=dev
          - npm test
          - npm run build
          - npm run deploy
          - echo "DONE!"
