# Media Centre Pipeline (CI)

image: ruby:2.4.0

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - cd ci
          - bash jiraUpdate.sh

definitions:
  caches:
    bundler: ./vendor
