# Media Centre Pipeline (CI)

image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cd www
          - npm install
          - npm test
          - npm run build || exit 1
          - npm run deploy || exit 1
          - echo "DONE!"
