# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Live Centre' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Live Centre
  pod 'ReachabilitySwift', '~> 3'
  pod 'AsyncSwift', '~> 2.0'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'Live CentreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Live CentreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
